# Generated by Django 5.1.3 on 2024-12-10 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0002_alter_flashcard_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to="flashcards.flashcardset",
            ),
        ),
    ]
